services:
  ollama-server:
    image: ollama/ollama:latest
    container_name: ollama-server
    pull_policy: missing
    ports:
      - "11434:11434"
    volumes:
      - /srv/docker-volumes/ollama_data:/root/.ollama
    environment:
      CUDA_VISIBLE_DEVICES: "0"
      OLLAMA_DEBUG: "0"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:v0.8.12
    container_name: ollama-webui
    pull_policy: missing
    restart: unless-stopped
    environment:
      OLLAMA_BASE_URL: "http://ollama-server:11434"
#     WEBUI_BASE_PATH: /open-webui
      ENABLE_ADMIN_CHAT_ACCESS: "false"
      ENABLE_ADMIN_EXPORT: "false"
      BYPASS_MODEL_ACCESS_CONTROL: "true"
    volumes:
      - /srv/docker-volumes/webui:/app/backend/data
    ports:
      - "3010:8080"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      ollama-server:
        condition: service_healthy

  mcp-bridge:
    build: .
    container_name: mcp-bridge
    environment:
      HOST: "0.0.0.0"
      PORT: "8000"
      MCP_USE_DEBUG: "0"
      OLLAMA_BASE_URL: "http://ollama-server:11434"
    env_file:
      - .env
    volumes:
#     - ./logs:/app/logs
      - /home/cirillo/workspace/mcp-national-rails:/app/servers/mcp-national-rail:ro
#     - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      bias-detector-service:
        condition: service_healthy
      ollama-server:
        condition: service_healthy

  bias-detector-service:
    container_name: bias-detector-service
    build:
      context: ../bias-detector-service
    environment:
      HOST: "0.0.0.0"
      PORT: "9090"
      HF_HOME: "/hf_cache"
      HF_OFFLINE: "false"
      MODEL_ID: "cardiffnlp/twitter-roberta-base-hate-latest"
      DEVICE: "cpu"
      MAX_LENGTH: "512"
      BATCH_SIZE: "8"
      THRESHOLD: "0.5"
      MAX_INPUT_CHARS: "20000"
      WARMUP: "true"
      MAX_LOADED_MODELS: "0"
      LOG_LEVEL: "INFO"
      SPAN_TRIGGERS: "always,never,all,nobody,everyone"

      # BIAS_CATEGORY_MAP_PATH: "/app/category_map.json"
      # BIAS_CATEGORY_MAP_JSON: '{"hate":["HATE","NOT-HATE"]}'

    expose:
      - "9090"
    restart: unless-stopped
    volumes:
      - hf-cache:/hf_cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9090/healthz"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  hf-cache: