services:
  mcp-bridge:
    build: .
    ports:
      - "8000:8000"
    environment:
      HOST: "0.0.0.0"
      PORT: "8000"
      DEBUG: "False"
     # used when gateway is in another container
      MCP_HOST: "http://locahost:9011/mcp"
    env_file:
      - .env
    volumes:
#      - ./logs:/app/logs
#      - /Users/roberto/python-test/mcp-national-rail:/app/servers/mcp-national-rails:ro
       - /home/cirillo/workspace/mcp-national-rail:/app/servers/mcp-national-rails:ro
#      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - gateway
  gateway:
    image: docker/mcp-gateway:dind
    privileged: true
    command:
      - --transport=sse
      - --servers=duckduckgo
      - --port=9011
      - --memory=512Mb
    network_mode: "host"

